project:
  type: website

website:
  title: "Personal Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: research.qmd
        text: Research
      - href: papers.qmd
        text: Papers
      - href: conferences.qmd
        text: Conferences
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About Me
  sidebar:
    style: "docked"
    logo: "./images/user_image.png"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com/IntelligentSystemsLaboratory
      - icon: twitter
        text: Twitter
        url: https://twitter.com/Bristol_AI_CDT
      - icon: envelope
        text: "{{< fa envelope >}} Email"
        url: mailto:ck22122@bristol.ac.uk
      - text: "{{< ai google-scholar >}} Google Scholar"
        url: https://scholar.google.com/citations?user=<google-scholar-user>
      - text: Pro-AI CDT
        url: https://www.bristol.ac.uk/cdt/interactive-ai/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



